#!/usr/bin/env bash
# sync-agent-rules.sh — single source of behavioral rules across agents.
#
# The canonical rules live in ../rules/. This script concatenates them into one
# generated file, AGENTS.shared.md, which each agent consumes through its own
# mechanism:
#
#   - Claude Code: CLAUDE.md imports the sources directly (`@rules/anti-patterns.md`).
#   - Pi:          a shell `pi` wrapper injects AGENTS.shared.md via --append-system-prompt.
#
# Edit the sources in ../rules/, re-run this script, and the change reaches every
# agent at once. Never edit AGENTS.shared.md by hand — it is generated.
#
# Run it from anywhere; paths are resolved relative to this script.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RULES_DIR="$ROOT/rules"
OUT="$ROOT/AGENTS.shared.md"

# Order matters: the most universal guardrails first, personal coaching last.
SOURCES=(
  "$RULES_DIR/anti-patterns.md"
  "$RULES_DIR/coaching.md"
)

for f in "${SOURCES[@]}"; do
  [ -f "$f" ] || { echo "missing source: $f" >&2; exit 1; }
done

{
  echo "<!-- GENERATED by scripts/sync-agent-rules.sh — DO NOT EDIT."
  echo "     Edit the sources in rules/ and re-run the script. -->"
  echo
  echo "# Shared Agent Rules"
  echo
  echo "Always-on behavioral rules for every agent (Claude Code, Pi)."
  echo
  for f in "${SOURCES[@]}"; do
    cat "$f"
    echo
    echo "---"
    echo
  done
} > "$OUT"

echo "wrote: $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"

# --- Optional install hooks --------------------------------------------------
# Point your real agent homes at the sources/output. Guarded by env vars so a
# fresh clone never touches your machine unless you ask it to.
#
#   CLAUDE_RULES_DIR=~/.claude/rules ./scripts/sync-agent-rules.sh
#     → copies the rule sources into Claude's rules dir (it imports them via CLAUDE.md).
#
#   PI_SHARED_TARGET=~/.pi/agent/AGENTS.md ./scripts/sync-agent-rules.sh
#     → symlinks Pi's AGENTS.md at the generated AGENTS.shared.md.

if [ -n "${CLAUDE_RULES_DIR:-}" ]; then
  mkdir -p "$CLAUDE_RULES_DIR"
  for f in "${SOURCES[@]}"; do cp "$f" "$CLAUDE_RULES_DIR/"; done
  echo "installed rule sources -> $CLAUDE_RULES_DIR"
fi

if [ -n "${PI_SHARED_TARGET:-}" ]; then
  ln -sfn "$OUT" "$PI_SHARED_TARGET"
  echo "linked: $PI_SHARED_TARGET -> $OUT"
fi
